name: MSVC-CI
on:
  push:
    branches: [ __main__ ]
  pull_request:
    branches: [ __main__ ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Build Directory
        run: |
         if (Test-Path build) { Write-Host "Build dir exists" } else { mkdir build }
        shell: pwsh
      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A Win32
      - name: Build Debug
        run: cmake --build build --config Debug
      - name: Build Release
        run: cmake --build build --config Release
      - name: Run Tests (Debug)
        run: cmake --build build --config Debug --target RUN_TESTS || cmake --build build --config Debug --target check
      - name: Run Tests (Release)
        run: cmake --build build --config Release --target RUN_TESTS || cmake --build build --config Release --target check
      - name: Upload Release Executables
        uses: actions/upload-artifact@v4
        with:
          name: pycdc-release
          path: build\Release\*.exe
          
